// <auto-generated />
using EmailClient.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmailClient.Database.Migrations
{
    [DbContext(typeof(EmailContext))]
    partial class EmailContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("EmailClient.Database.EmailEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<byte[]>("Email")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("email");

                    b.Property<string>("Filter")
                        .HasColumnType("TEXT")
                        .HasColumnName("filter");

                    b.HasKey("Id");

                    b.ToTable("emails", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
